# Site settings
title: Austin Erlandson
email: austin@erlandson.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a graduate of Nashville Software School's Cohort-8.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: AustinErlandson
github_username:  erlandsona

# Build settings
markdown: kramdown
