# Site settings
title: Austin Erlandson
email: austin@erlandson.com
url: https://erlandsona.github.io
description: "Portfolio site of Austin Erlandson, FullStack Web-Developer."

# Footer settings
footer: austin.erlandson.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/erlandsona
  - title: bitbucket
    url: https://bitbucket.org/erlandsona
  - title: codepen
    url: https://codepen.io/erlandsona/
  - title: linkedin
    url: https://www.linkedin.com/in/erlandsona
  - title: facebook
    url: https://www.facebook.com/austin.erlandson
  - title: twitter
    url: https://twitter.com/AustinErlandson

# Build settings
sass:
  style: compressed
markdown: kramdown
permalink: pretty
